name       : just
version    : 0.5.10
release    : 3
source     :
    - https://github.com/casey/just/archive/v0.5.10.tar.gz : ae8219cecad107c296e41b486e1966f0c19ae3222fb29d3738aeaa3c34e4a431
license    : CC0-1.0
component  : programming.tools
summary    : Just a command runner
description: |
    Just is a handy way to save and run project-specific commands.
networking : true
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/just $installdir/usr/bin/just
