name       : just
version    : 0.5.7
release    : 2
source     :
    - https://github.com/casey/just/archive/v0.5.7.tar.gz : 845191d47a1da8a26491d411c03ce2de3d26a9e973d9b71c6be23bae896ccc94
license    : CC0-1.0
component  : programming.tools
summary    : Just a command runner
description: |
    Just is a handy way to save and run project-specific commands.
networking : true
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm755 target/release/just $installdir/usr/bin/just
