name       : just
version    : 0.10.1
release    : 20
source     :
    - https://github.com/casey/just/archive/refs/tags/0.10.1.tar.gz : e60e61d34fdaaa94aa9c4fa6fc4cd5ce07628758db989d15f97ce7b70d36fecd
license    : CC0-1.0
component  : programming.tools
homepage   : https://github.com/casey/just/
summary    : Just a command runner
description: |
    Just is a handy way to save and run project-specific commands. As it's a command runner, not a build system, it avoids many of Make's complexities and idiosyncrasies.
networking : true
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/just $installdir/usr/bin/just
