name       : just
version    : 0.9.2
release    : 15
source     :
    - https://github.com/casey/just/archive/refs/tags/v0.9.2.tar.gz : 0f064d0ea9f3d8bbcd84c5e6a85243738bdb6f49d059f589fd6928c64ea6fb64
license    : CC0-1.0
component  : programming.tools
homepage   : https://github.com/casey/just/
summary    : Just a command runner
description: |
    Just is a handy way to save and run project-specific commands. As it's a command runner, not a build system, it avoids many of Make's complexities and idiosyncrasies.
networking : true
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/just $installdir/usr/bin/just
