name       : just
version    : 0.6.0
release    : 5
source     :
    - https://github.com/casey/just/archive/v0.6.0.tar.gz : 412a8c98537022909600968b1458af9f13e51372bad2c6816cb26a1704387c90
license    : CC0-1.0
component  : programming.tools
summary    : Just a command runner
description: |
    Just is a handy way to save and run project-specific commands.
networking : true
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/just $installdir/usr/bin/just
